"""add kinopoisk_url to films

Revision ID: 04572a67037e
Revises: c1784ebef74d
Create Date: 2026-06-07 23:55:46.641257
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04572a67037e'
down_revision: Union[str, None] = 'c1784ebef74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('kinopoisk_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'kinopoisk_url')
    # ### end Alembic commands ###
