"""add exclude_family_from_recommendations to users

Revision ID: 1291548e2f31
Revises: 7ab4cb88220e
Create Date: 2026-06-10 10:19:12.921873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1291548e2f31'
down_revision: Union[str, None] = '7ab4cb88220e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exclude_family_from_recommendations', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exclude_family_from_recommendations')
    # ### end Alembic commands ###
