"""add series table and episode fields

Revision ID: 48634499438a
Revises: edcba9876543
Create Date: 2026-06-14 11:32:07.320085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48634499438a'
down_revision: Union[str, None] = 'edcba9876543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.add_column('films', sa.Column('series_id', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('season_number', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.add_column('films', sa.Column('episode_title', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_films_series_id'), 'films', ['series_id'], unique=False)
    op.create_foreign_key(None, 'films', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.drop_index(op.f('ix_films_series_id'), table_name='films')
    op.drop_column('films', 'episode_title')
    op.drop_column('films', 'episode_number')
    op.drop_column('films', 'season_number')
    op.drop_column('films', 'series_id')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
