"""add incognito columns to users and watch_events

Revision ID: 5342f2fca41e
Revises: 55d833302f6b
Create Date: 2026-06-10 09:51:49.204700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5342f2fca41e'
down_revision: Union[str, None] = '55d833302f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('incognito', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('watch_events', sa.Column('incognito', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_events', 'incognito')
    op.drop_column('users', 'incognito')
    # ### end Alembic commands ###
