"""add is_family_video to films

Revision ID: 7ab4cb88220e
Revises: 5342f2fca41e
Create Date: 2026-06-10 10:06:25.836716
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab4cb88220e'
down_revision: Union[str, None] = '5342f2fca41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('is_family_video', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'is_family_video')
    # ### end Alembic commands ###
