"""add age_rating to films, age_group to users

Revision ID: 9dadfa94c2ae
Revises: 1eacde9e15e5
Create Date: 2026-06-10 09:32:39.746560
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dadfa94c2ae'
down_revision: Union[str, None] = '1eacde9e15e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('age_rating', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('age_group', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age_group')
    op.drop_column('films', 'age_rating')
    # ### end Alembic commands ###
