"""add filter_by_language to users

Revision ID: c6678f604e6b
Revises: e8a5340bd6ce
Create Date: 2026-06-10 12:26:55.277825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6678f604e6b'
down_revision: Union[str, None] = 'e8a5340bd6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filter_by_language', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'filter_by_language')
    # ### end Alembic commands ###
