"""add include_external to users

Revision ID: e8a5340bd6ce
Revises: 2483a1da837f
Create Date: 2026-06-10 11:56:48.953004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a5340bd6ce'
down_revision: Union[str, None] = '2483a1da837f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('include_external', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'include_external')
    # ### end Alembic commands ###
